version: '2'
services:
  web:
    extends:
      file: docker-compose-base.yml
      service: base
    environment:
      - CABOT_PLUGINS_ENABLED=cabot_alert_email
      - DEBUG=t
      - DATABASE_URL=postgres://postgres@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=cabot.settings
      - LOG_FILE=/dev/null
      - PORT=5001
      - TIME_ZONE=Europe/Berlin
      - ADMIN_EMAIL=mathiasuhl@gmx.de
      - CABOT_FROM_EMAIL=mathiasuhl@gmx.de
      - CALENDAR_ICAL_URL=http://www.google.com/calendar/ical/example.ics
      - CELERY_BROKER_URL=redis://redis:6379/1
      - DJANGO_SECRET_KEY=2FL6ORhHwr5eX34p3424234P9mMugnIOd3jzVuT45f7w430Mt5PnEwbcJgma0q8zUXNZ68A
      - HTTP_USER_AGENT=Cabot
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - WWW_HTTP_HOST=192.168.40.141
      - WWW_SCHEME=http
    command: python manage.py runserver 0.0.0.0:5001
    ports:
      - "5001:5001"
    links:
      - redis
      - db

  worker:
    extends:
      file: docker-compose-base.yml
      service: base
    command: celery worker -A cabot --loglevel=DEBUG --concurrency=16 -Ofair
    environment:
      - SKIP_INIT=1
      - WAIT_FOR_MIGRATIONS=1
      - CABOT_PLUGINS_ENABLED=cabot_alert_email
      - DEBUG=t
      - DATABASE_URL=postgres://postgres@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=cabot.settings
      - LOG_FILE=/dev/null
      - PORT=5001
      - TIME_ZONE=Europe/Berlin
      - ADMIN_EMAIL=mathiasuhl@gmx.de
      - CABOT_FROM_EMAIL=mathiasuhl@gmx.de
      - CALENDAR_ICAL_URL=http://www.google.com/calendar/ical/example.ics
      - CELERY_BROKER_URL=redis://redis:6379/1
      - DJANGO_SECRET_KEY=2FL6ORhHwr5eX34p3424234P9mMugnIOd3jzVuT45f7w430Mt5PnEwbcJgma0q8zUXNZ68A
      - HTTP_USER_AGENT=Cabot
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - WWW_HTTP_HOST=192.168.40.141
      - WWW_SCHEME=http
    links:
      - redis
      - db

  beat:
    extends:
      file: docker-compose-base.yml
      service: base
    command: celery beat -A cabot --loglevel=DEBUG
    environment:
      - CABOT_PLUGINS_ENABLED=cabot_alert_email
      - DEBUG=t
      - DATABASE_URL=postgres://postgres@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=cabot.settings
      - LOG_FILE=/dev/null
      - PORT=5001
      - TIME_ZONE=Europe/Berlin
      - ADMIN_EMAIL=mathiasuhl@gmx.de
      - CABOT_FROM_EMAIL=mathiasuhl@gmx.de
      - CALENDAR_ICAL_URL=http://www.google.com/calendar/ical/example.ics
      - CELERY_BROKER_URL=redis://redis:6379/1
      - DJANGO_SECRET_KEY=2FL6ORhHwr5eX34p3424234P9mMugnIOd3jzVuT45f7w430Mt5PnEwbcJgma0q8zUXNZ68A
      - HTTP_USER_AGENT=Cabot
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - WWW_HTTP_HOST=192.168.40.141
      - WWW_SCHEME=http
      - SKIP_INIT=1
      - WAIT_FOR_MIGRATIONS=1
    links:
      - redis
      - db

  redis:
    image: redis:alpine

  db:
    image: postgres:alpine
    volumes:
      - /mnt/data/docker/cabot/postgresql:/var/lib/postgresql/data

volumes:
  datavolume:
      - /mnt/data/docker/cabot
